name: devel-compile

on:
  push:
    branches:
    - devel
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: |
          mkdir build
          cd build
          cmake ..
          make
          cp pinus-flexilis ..
      - name: upload artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: linux-x86_64
          path: |
            pinus-flexilis
            EEPROM.BIN
            config.ini
